### PR TITLE
feat: Degruntify football-assets and use TypeScript instead.

### PR DESCRIPTION
**Pull request by AshCorr**
<div class="expandable unchanged js-expandable rich-diff-level-zero">
<h2 class="unchanged rich-diff-level-one">What does this change?</h2>
<p class="unchanged rich-diff-level-one">Completely removes Grunt from this project in favour of using a custom script to resize, compress, and upload images to our football assets bucket.</p>
<p><b>Note:</b> for some reason I wasn't able to get the images quite as small as they were 
 when we were using Grunt, in most images the difference is less than 1KB in size.</p>
<p>Closes <a href="https://github.com/guardian/dotcom-rendering/issues/6857">6857</p>
<p class="unchanged rich-diff-level-one"><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224372190-96d3d99b-226c-4677-8bdf-4e66845056c9.png">image</a></p>
<h2 class="unchanged rich-diff-level-one">How to test</h2>
<p class="unchanged rich-diff-level-one"><code class="notranslate">npm run prepare</code> will generate all images and save them to <code class="notranslate">build/</code>, you can then take these images and compare them to what is already in the S3 bucket.</p>
<h2 class="unchanged rich-diff-level-one">Benefits</h2>
<ul class="unchanged rich-diff-level-one">
<li class="unchanged">No longer rely on git submodules for binary dependencies</li>
<li class="unchanged">No longer rely on other tools being installed by brew</li>
<li class="unchanged">No longer rely on un-maintained grunt plugins such as <code class="notranslate">grunt-aws-s3</code> which locks us into a specific version of Grunt.</li>
<li class="unchanged">Who wants to use Grunt in this day and age?</li>
</ul>
<h2 class="unchanged rich-diff-level-one">Images</h2>
<h3 class="unchanged rich-diff-level-one">120px wide images</h3>
<table role="table" class="unchanged rich-diff-level-one">
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224375490-0a1ceec2-62d9-406c-af60-73a7872a0c7e.png">before120_0</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224372910-6ba4db4f-0111-4975-86d2-858384a745e6.png">after120_0</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224375520-f038935d-6878-4a8a-a3b0-d25899b18eca.png">before120_1</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224372947-065f9ed2-ec7d-4f32-a0d2-57959faac56e.png">after120_1</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224375556-bceb7cf0-67dd-4da1-9d10-e126a0744df9.png">before120_2</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224372991-1fa083cc-17db-4dbd-b54c-4de645dfbbc6.png">after120_2</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224375597-ca7aaadb-139d-407b-ad76-f18f1061f306.png">before120_3</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224373032-9ef36cae-8bc9-433c-bc79-ed90760065a1.png">after120_3</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224375646-9429220c-26f1-4736-b272-562036da10ce.png">before120_4</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224373081-fd1ee2e9-92d0-4da6-a95c-c30511b9e424.png">after120_4</a></td>
</tr>
</tbody>
</table>
<h3 class="unchanged rich-diff-level-one">60px wide images</h3>
</div>
<table role="table" class="changed rich-diff-level-zero"> <thead class="rich-diff-level-one"> <tr>
<th>Before</th>
<th>After</th>
</tr> </thead> <tbody class="changed rich-diff-level-one">
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224376089-2c32ce24-ee02-4a46-b221-e97bcd818436.png">before60_0</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224374822-ede9682c-0b4d-4f56-956c-b2dfb35370cb.png">after60_0</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224376134-6a7c38b4-7395-48a0-9399-0bad6cd520ca.png">before60_1</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224374849-bd6e90b9-5bd2-49cd-b3dc-8b16f47932a4.png">after60_1</a></td>
</tr>
<tr class="changed">
<td class="changed">
<a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224376151-a9c60841-29d8-4a03-8b8a-697423f31d7d.png">before60_2</a>
</td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224374881-0bd0ad3b-a0a0-4d0e-a19a-727a6441a4eb.png">after60_2</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224376177-3e699811-3c60-48de-87ac-a9607f8d7a44.png">before60_3</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224374935-078b3a56-d0df-4842-b843-ae938266da06.png">after60_3</a></td>
</tr>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224376210-5fb6f523-6af5-4e3b-9edb-3df4ff2d8d57.png">before60_4</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/21217225/224374961-f0cb252d-e091-49f8-bf27-2764d52f5273.png">after60_4</a></td>
</tr>
</tbody> </table>

### CODE REVIEW

**Review by mxdvl — COMMENTED** [review]
Sharp!

Latest versions of node support top-level await, I believe.

**Comment by AshCorr** [comment]
> Latest versions of node support top-level await, I believe.

Yes! But CommonJS doesn't seem to let you use top-level await 🤔 I spent a while fiddling with `ts-node` options trying to get top level await to work but wasn't able to! Got any time on Monday to pair perhaps?

**Comment by AshCorr** [comment]
Hijacking my PR I see @mchv ;)

The new images look a bit less fuzzy than the old ones (I think? Might just be my mind playing tricks on me), I'll take a look at the resizer settings again on monday.

**Comment by mxdvl** [comment]
@AshCorr – the new images are also crisper to my eye. Unsurprising from a library called `sharp`.

@mchv – should the addition of the LICENSE not be its own PR?

**Comment by mchv** [comment]
This is great work @AshCorr! I have noticed [`ISC` license](https://opensource.org/license/isc-license-txt/) in the package, so quickly updated license to match the one we recommend

**Comment by AshCorr** [comment]
The old image optimizer (pngquant) some very different PNG quality settings than Sharp so just directly copying the values would not work. After tinkering around a while with Sharp I was able to come up with some very similar file sizes where I could not tell the difference.

| Before | After | Before (bytes) | After (bytes) |
|--------|-------|--------|-------|
| ![before_102][] | ![after_102][] | 6328 | 6370 |

[before_102]: https://user-images.githubusercontent.com/21217225/224784546-6e352294-8028-4bf7-8c53-efa9a29b7afd.png

[after_102]: https://user-images.githubusercontent.com/21217225/224784403-4df0e3e3-5b33-4a18-90d0-59c5db94088d.png

**Comment by AshCorr** [comment]
Hope you don't mind, but I've moved your changes to a separate PR https://github.com/guardian/football-assets/pull/88 @mchv ! This PR is already a bit loaded with changes!

**Review by OllysCoding — APPROVED** [review]
+1 This is a great refactor, super tidy & much more understandable!

**Pull request merged**
