### PR TITLE
Added Vorskla Poltava FC [38301] and MOL Vidi FC [38429]

### PR DESCRIPTION
**Pull request by paperboyo**
If someone could be kind enough to run the grunt thingie, please? Thx!

### CODE REVIEW

**Comment by webb04** [comment]
We might need Vidi FC too who play Chelsea in a few weeks https://www.theguardian.com/football/match/4098683

**Comment by paperboyo** [comment]
I cannot find PA ID through https://frontend.gutools.co.uk/troubleshoot/football for this club, though. Would you know how, @webb04?

**Comment by paperboyo** [comment]
OK, got it: 38429. Will update this branch…

**Comment by webb04** [comment]
Great, I noticed there's a few others (but they probably won't get as much coverage if not playing against a big team). Could be nice if dotcom had a generic badge fallback like the apps do 
img_5906

**Comment by paperboyo** [comment]
Oh, I hate football! Added those too (one bad quality). Dotcom should also request them through image resizer, so that we could get rid of this whole repo…

**Comment by webb04** [comment]
_Akhisarspor_ and _Sarpsborg_ 08 should be the last remaining blanks I can see 😅

**Comment by webb04** [comment]
But yeah this will happen every year I imagine, so would make sense to get rid of it!

**Comment by paperboyo** [comment]
Added last two. Not adding anything more! Let’s just ban football instead. Make it an underground sport. No logos, just plain grey clothes, like cigarette packets ;-)

**Pull request merged**
